name: Promote staging → main (open PR)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR with gh
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}         
        run: |
          # Create the PR, or show the existing one if already open
          gh pr create --repo "$REPO" --base main --head staging \
            --title "Promote staging to main" \
            --body "Manual QA complete on staging. Promote to production." \
          || gh pr list --repo "$REPO" --base main --head staging --state open
